// Add your Gemini API key here (get it from https://makersuite.google.com/app/apikey)
const GEMINI_API_KEY = 'AIzaSyCFNJZETNa6bkAlAAjRIDsDLyQSxW4HoTY';

const textInput = document.getElementById('textInput');
const charCount = document.getElementById('charCount');
const analyzeBtn = document.getElementById('analyzeBtn');
const resultSection = document.getElementById('resultSection');
const percentageValue = document.getElementById('percentageValue');
const progressCircle = document.getElementById('progressCircle');
const verdict = document.getElementById('verdict');
const detailsContent = document.getElementById('detailsContent');

// Character counter
textInput.addEventListener('input', () => {
    const count = textInput.value.length;
    charCount.textContent = count;
});

// Analyze button click
analyzeBtn.addEventListener('click', async () => {
    const text = textInput.value.trim();

    if (!text) {
        alert('Please enter some text to analyze.');
        return;
    }

    if (text.length < 50) {
        alert('Please enter at least 50 characters for accurate analysis.');
        return;
    }

    await analyzeText(text, GEMINI_API_KEY);
});

async function analyzeText(text, apiKey) {
    // Show loading state
    analyzeBtn.disabled = true;
    analyzeBtn.classList.add('loading');
    resultSection.classList.add('hidden');

    try {
        const result = await callGeminiAPI(text, apiKey);
        displayResults(result);
    } catch (error) {
        alert('Error: ' + error.message);
    } finally {
        analyzeBtn.disabled = false;
        analyzeBtn.classList.remove('loading');
    }
}

async function callGeminiAPI(text, apiKey) {
    const url = `https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=${apiKey}`;
    
    const prompt = `Analyze the following text and determine if it was generated by AI or written by a human. 
Provide your response in the following JSON format only, with no additional text:
{
    "percentage": <number between 0-100>,
    "confidence": "<high/medium/low>",
    "reasoning": "<brief explanation>",
    "indicators": ["<indicator1>", "<indicator2>", "<indicator3>"]
}

Where:
- percentage: 0 means definitely human-written, 100 means definitely AI-generated
- confidence: your confidence level in this assessment
- reasoning: brief explanation of your conclusion
- indicators: specific patterns or characteristics that led to your conclusion

Text to analyze:
"""
${text}
"""`;

    const response = await fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({
            contents: [{
                parts: [{
                    text: prompt
                }]
            }],
            generationConfig: {
                temperature: 0.2,
                topK: 40,
                topP: 0.95,
                maxOutputTokens: 1024,
            }
        })
    });

    if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error?.message || 'Failed to analyze text. Please check your API key.');
    }

    const data = await response.json();
    
    // Log the response for debugging
    console.log('API Response:', data);
    
    // Check if response has the expected structure
    if (!data.candidates || !data.candidates[0] || !data.candidates[0].content) {
        throw new Error('Unexpected API response structure');
    }
    
    const generatedText = data.candidates[0].content.parts[0].text;
    
    // Extract JSON from the response - handle markdown code blocks
    let jsonMatch = generatedText.match(/```json\s*([\s\S]*?)\s*```/);
    if (!jsonMatch) {
        jsonMatch = generatedText.match(/\{[\s\S]*\}/);
    } else {
        jsonMatch[0] = jsonMatch[1];
    }
    
    if (!jsonMatch) {
        console.error('Generated text:', generatedText);
        throw new Error('Could not extract JSON from API response. Check console for details.');
    }
    
    return JSON.parse(jsonMatch[0]);
}

function displayResults(result) {
    const percentage = Math.round(result.percentage);
    
    // Animate percentage
    animatePercentage(percentage);
    
    // Update progress circle
    const circumference = 2 * Math.PI * 90;
    const offset = circumference - (percentage / 100) * circumference;
    progressCircle.style.strokeDashoffset = offset;
    
    // Determine verdict
    let verdictClass, verdictIcon, verdictText;
    if (percentage < 30) {
        verdictClass = 'human';
        verdictIcon = '✓';
        verdictText = 'Likely Human-Written';
    } else if (percentage < 70) {
        verdictClass = 'mixed';
        verdictIcon = '⚠';
        verdictText = 'Mixed or Uncertain';
    } else {
        verdictClass = 'ai';
        verdictIcon = '🤖';
        verdictText = 'Likely AI-Generated';
    }
    
    verdict.className = `verdict ${verdictClass}`;
    verdict.querySelector('.verdict-icon').textContent = verdictIcon;
    verdict.querySelector('.verdict-text').textContent = verdictText;
    
    // Display details
    let detailsHTML = `
        <p><strong>Confidence Level:</strong> ${result.confidence.toUpperCase()}</p>
        <p><strong>Analysis:</strong> ${result.reasoning}</p>
        <p><strong>Key Indicators:</strong></p>
        <ul>
    `;
    
    result.indicators.forEach(indicator => {
        detailsHTML += `<li>${indicator}</li>`;
    });
    
    detailsHTML += '</ul>';
    detailsContent.innerHTML = detailsHTML;
    
    // Show results
    resultSection.classList.remove('hidden');
    resultSection.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}

function animatePercentage(targetPercentage) {
    let currentPercentage = 0;
    const duration = 1000;
    const increment = targetPercentage / (duration / 16);
    
    const timer = setInterval(() => {
        currentPercentage += increment;
        if (currentPercentage >= targetPercentage) {
            currentPercentage = targetPercentage;
            clearInterval(timer);
        }
        percentageValue.textContent = Math.round(currentPercentage);
    }, 16);
}
